version: "3"
services:
  mongodb:
    image: mongo:latest    
    networks: 
      - nodeapp-network    
    ports:
      - "27017:27017"
  mongodb-seed:    
    build : 
      context: .
      dockerfile: mongoseed.Dockerfile      
    networks: 
      - nodeapp-network   
    depends_on:
      - mongodb
  node:
    build :
      context: .
      dockerfile: node.Dockerfile
    ports: 
      - "3000:3000"
    networks: 
      - nodeapp-network    
    depends_on:
      - mongodb

networks: 
    nodeapp-network:
      driver : bridge 

      