version: "2"
services:
  node:
    build :
      context: .
      dockerfile: node.Dockerfile
    ports: 
      - "3000:3000"
    networks: 
      - nodeapp-network    
  mongodb:
    build :
      context: .
      dockerfile: mongo.Dockerfile  
    networks: 
      - nodeapp-network    
    ports:
      - "27017:27017"
    env_file:
      - ./.docker/env/mongo.env

networks: 
    nodeapp-network:
      driver : bridge 